name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0 # Specify the Zig version you want to use

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test
